version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@2.0.0

parameters:
  run_integration_tests:
    description: An internal flag to prevent integration local test from running before a development version has been created.
    type: boolean
    default: false

jobs:
  test_local_invoke:
    executor: sam/default
    steps:
      - checkout
      - sam/install:
          aws-access-key-id: AWS_ACCESS_KEY_ID_DEV
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_DEV
      - sam/local-start-api:
          template: "./sam-app/template.yaml"
          endpoint: "hello"
          debug: false

workflows: 
  integration_local_test:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
      - test_local_invoke
  delivery_deploy_app_dev:
    jobs:
      - sam/deploy:
          capabilities: '"CAPABILITY_IAM"'
          name: deploy-app-dev
          template: "./sam-app/template.yaml"
          stack-name: "sam-deploy-app-dev"
          s3-bucket: "testing-orbs-yastani-dev"
          filters:
            branches:
              only:
                - main
  delivery_deploy_app_prod:
    jobs:
      - sam/deploy:
          capabilities: '"CAPABILITY_IAM"'
          name: deploy-app-prod
          template: "./sam-app/template.yaml"
          stack-name: "sam-deploy-app-prod"
          s3-bucket: "testing-orbs-yastani"
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^v\d+\.\d+\.\d+$/