version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@2.0.0
  slack: circleci/slack@4.0
  orb-tools: circleci/orb-tools@10.0

jobs:
  test_local_invoke:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - sam/local-start-api:
          template: "./sam-app/template.yaml"
          endpoint: "hello"
  notify:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          message: test

workflows:
  test-pack:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - notify
      - hold-for-dev-publish:
          type: approval
          requires:
            - orb-tools/lint
            - orb-tools/pack
      #- orb-tools/publish-dev:
      #    orb-name: circleci/aws-sam-serverless
      #    context: orb-publishing
      #    requires:
      #      - hold-for-dev-publish
      #- orb-tools/trigger-integration-tests-workflow:
      #    name: trigger-integration-dev
      #    context: orb-publishing
      #    requires:
      #      - orb-tools/publish-dev
