version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@2.0.0

parameters:
  run_integration_tests:
    description: An internal flag to prevent integration local test from running before a development version has been created.
    type: boolean
    default: true

jobs:
  test_local_invoke:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - sam/local-start-api:
          template: "./sam-app/template.yaml"
          endpoint: "hello"
          debug: false
  deploy_app_dev:
    executor: sam/default
    steps:
      - sam/deploy:
          #capabilities: '"CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"'
          name: deploy-app-dev
          template: "./sam-app/template.yaml"
          stack-name: "orb-deploy-app-dev"
          #s3-bucket: "testing-orbs-yastani"

workflows: 
  integration_local_test:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
      - test_local_invoke
  delivery_deploy_app:
    jobs:
      - deploy_app_dev