version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@2.0.0
jobs:
  sam:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - sam/local-start-api:
          template: "./sam-app/template.yaml"
          endpoint: "hello"
workflows:
  build_and_test:
    jobs:
      - sam