version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@2.0.0
jobs:
  build_and_package:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - sam/local-start-api
workflows: null
