version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@2.0.0
  slack: circleci/slack@3.4.2

jobs:
  send_approval_link:
    executor: slack/default
    steps:
      - slack/notify:
          message: |
            Please check and approve Job to deploy.
            https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}
          webhook: https://hooks.slack.com/services/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
  test_hello_api:
    executor: sam/default
    steps:
      - run: echo "hello test"

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - sam/build:
          name: build stage
          stack-name: build-production
          aws-region: ap-northeast-1
          template: aws-sam-serverless/sam-app/template.yaml
          debug: true

      - send_approval_link:
          requires:
            - sam/build
          filters:
            branches:
              only: main

      - manual_approval:
          type: approval
          requires:
            - send_approval_link
          filters:
            branches:
              only: main

      - sam/deploy:
          requires:
            - manual_approval
          filters:
            branches:
              only: main
          name: deploy stage
          stack-name: deploy-production
          aws-region: ap-northeast-1
          template: aws-sam-serverless/sam-app/template.yaml